<?php

namespace ProcessMaker\Package\PackageTranslations\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use ProcessMaker\Package\PackageTranslations\Enums\StatusEnum;
use ProcessMaker\Package\PackageTranslations\Models\Translatable;

class TranslatableModelFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return string
     */
    public function modelName()
    {
        return Translatable::class;
    }

    /**
     * {@inheritdoc}
     */
    public function definition()
    {
        return [
            'language_code' => 'fa',
        ];
    }
}
